import math
import struct
import wave
from pathlib import Path
from typing import Iterable, List, Tuple

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import MusicTrack
from app.services.storage import ensure_storage_dirs, storage_root


SAMPLE_RATE = 44_100
DURATION_SECONDS = 16.0

TrackSpec = Tuple[str, str, List[Tuple[float, float, float]]]

SYSTEM_MUSIC_TRACKS: List[TrackSpec] = [
    (
        "System Bright Pulse",
        "system-bright-pulse.wav",
        [
            (261.63, 329.63, 392.0),
            (293.66, 369.99, 440.0),
            (329.63, 392.0, 493.88),
            (392.0, 493.88, 587.33),
        ],
    ),
    (
        "System Calm Bed",
        "system-calm-bed.wav",
        [
            (220.0, 277.18, 329.63),
            (196.0, 246.94, 293.66),
            (174.61, 220.0, 261.63),
            (196.0, 246.94, 329.63),
        ],
    ),
    (
        "System Clean Drive",
        "system-clean-drive.wav",
        [
            (329.63, 415.3, 493.88),
            (246.94, 311.13, 369.99),
            (293.66, 369.99, 440.0),
            (220.0, 277.18, 329.63),
        ],
    ),
    (
        "System Soft Resolve",
        "system-soft-resolve.wav",
        [
            (174.61, 261.63, 329.63),
            (196.0, 293.66, 349.23),
            (220.0, 329.63, 392.0),
            (164.81, 246.94, 329.63),
        ],
    ),
]


def seed_generated_system_music(db: Session) -> int:
    ensure_storage_dirs()
    music_dir = storage_root() / "music"
    music_dir.mkdir(parents=True, exist_ok=True)

    for title, filename, progression in SYSTEM_MUSIC_TRACKS:
        path = music_dir / filename
        if not path.exists() or path.stat().st_size == 0:
            write_track(path=path, progression=progression)
        track = db.scalar(
            select(MusicTrack).where(
                MusicTrack.title == title,
                MusicTrack.scope == "system",
            )
        )
        if track is None:
            track = MusicTrack(
                user_id=None,
                title=title,
                original_filename=filename,
                stored_filename=filename,
                file_path=str(path),
                mime_type="audio/wav",
                scope="system",
                is_active=True,
            )
            db.add(track)
        track.stored_filename = filename
        track.file_path = str(path)
        track.file_size_bytes = path.stat().st_size
        track.duration_seconds = DURATION_SECONDS
        track.artist = "Flashcutter"
        track.license_name = "Internal generated test audio"
        track.license_url = None
        track.source_url = None
        track.attribution_text = "Generated by Flashcutter for local MVP testing."
        track.mood = "test"
        track.bpm = None
        track.is_active = True
    db.commit()
    return len(SYSTEM_MUSIC_TRACKS)


def write_track(path: Path, progression: Iterable[Tuple[float, float, float]]) -> None:
    chords = list(progression)
    total_samples = int(SAMPLE_RATE * DURATION_SECONDS)
    chord_samples = max(1, total_samples // len(chords))

    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(SAMPLE_RATE)
        for sample_index in range(total_samples):
            t = sample_index / SAMPLE_RATE
            chord = chords[min(sample_index // chord_samples, len(chords) - 1)]
            local = (sample_index % chord_samples) / chord_samples
            envelope = smooth_envelope(local)
            beat = 0.55 + 0.45 * max(0.0, math.sin(2 * math.pi * 2 * t))
            value = 0.0
            for frequency in chord:
                value += math.sin(2 * math.pi * frequency * t) * 0.18
                value += math.sin(2 * math.pi * frequency * 2 * t) * 0.035
            bass_frequency = chord[0] / 2
            value += math.sin(2 * math.pi * bass_frequency * t) * 0.22 * beat
            sample = int(max(-0.92, min(0.92, value * envelope)) * 32767)
            wav.writeframes(struct.pack("<h", sample))


def smooth_envelope(local: float) -> float:
    attack = min(1.0, local / 0.08)
    release = min(1.0, (1.0 - local) / 0.12)
    return max(0.0, min(1.0, attack, release))
